<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Applicant extends Model
{
    use HasFactory;
    protected $fillable = [
        'total_document',
        'applicant_name',
        'passport_number',
        'applicant_email',
        'employee_number',
        'ta_va_number',
        'agent_name',
        'tp_form_upload',
        'outstation_name',
        'dob',
        'location',
        'company_name',
        'country',
        'appointment_date',
        'category',
        'rec_date',
        'sub_date',
        'coll_date',
        'sent_date',
        'referer',
        'dd_received1',
        'dd_received2',
        'mobile_number',
        'status',
        'Outstation',
        'passportCheck',
        'photoCount',
        'visaFormCheck',
        'declarationCheck',
        'healthDeclarationCheck',
        'vfsDeclarationCheck',
        'coveringLetterCheck',
        'coveringLetterFromDate',
        'coveringLetterToDate',
        'invitationLetterCheck',
        'invitationLetterFromDate',
        'invitationLetterToDate',
        'personalBankStatementCheck',
        'personalBankStatementDate',
        'personalITReturnsCheck',
        'personalITReturnsDate',
        'companyBankStatementCheck',
        'companyBankStatementDate',
        'companyITReturnsCheck',
        'companyITReturnsDate',
        'payslipCheck',
        'payslipOption',
        'ticketReservationCheck',
        'ticketReservationFromDate',
        'ticketReservationToDate',
        'insuranceForTravelCheck',
        'insuranceForTravelFromDate',
        'insuranceForTravelToDate',
        'hotelBookingCheck',
        'hotelBookingFromDate',
        'hotelBookingToDate',
        'yellowFeverCardCheck',
        'chamberOfCommerceCheck',
        'forexReceiptCheck',
        'ddCheck',
        'ddDate',
        'ddNumber',
        'addressProofCheck',
        'remarks',
        'internal_remarks',
        'send_sms',

       
    ];
}
